seed: 42

wandb:
  enabled: true
  project: rna-one-d-3d
  name: a800-card1-1024-centered
  entity:
  mode: online

data:
  source: cif_all_atom
  sequences_csv: "/home/weisx/workdir/igem one-model/stanford-rna-3d-folding-data/train_sequences.v2.csv"
  cif_dir: "/home/weisx/workdir/igem one-model/stanford-rna-3d-folding-data/PDB_RNA"
  max_records:
  max_sequence_length: 1024
  min_atom_coverage: 0.5
  center_coordinates: true

model:
  type: rhofold
  d_model: 512
  nhead: 8
  num_e2e_layers: 8
  num_structure_layers: 4
  dim_feedforward: 2048
  dropout: 0.1
  max_len: 2048
  pair_dim: 256
  msa_dim: 256
  num_distance_bins: 32
  recycle_iters: 2
  sequence_loss_initial_weight: 0.1

optimizer:
  lr: 0.0002
  weight_decay: 0.01
  min_lr: 0.000001
  warmup_steps: 200
  coord_mse_weight: 0.1
  pairwise_weight: 0.1
  pair_ce_weight: 0.1
  fape_weight: 0.05
  clash_weight: 0.02
  bond_weight: 0.05
  angle_weight: 0.02
  torsion_weight: 0.02
  confidence_weight: 0.01

trainer:
  accelerator: gpu
  cuda_device: 1
  batch_size: 32
  num_workers: 16
  max_epochs: 50
  val_fraction: 0.05
  checkpoint_dir: checkpoints_3d_a800_card1
  show_progress: true
  mixed_precision: true
  accumulate_grad_batches: 1
  gradient_clip_norm: 1.0
  sequence_mask_probability: 0.15
  scaffold_mask_probability: 0.25
  motif_length: 16
